version: '3.4'

services:
  identitydb:
    container_name: identitydb
    environment:
        SA_PASSWORD: "Murat123*"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1435:1433"

  bankaccountdb:
    container_name: bankaccountdb
    environment:
        SA_PASSWORD: "Murat123*"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1436:1433"



  bankaccount.api:
    container_name: bankaccount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:BankAccountDb=Server=bankaccountdb;Database=GringottsBankAccountDb;User Id=sa;Password=Murat123*"
      - IdentityServerUrl=http://gringottsbank.identityserver
    ports:
      - "8010:80"
    depends_on:
      - bankaccountdb

  gringottsbank.identityserver:
    container_name: gringottsbank.identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb;Database=GringottsIdentityDb;User Id=sa;Password=Murat123*"
    ports:
      - "8001:80"
    depends_on:
      - identitydb

